### ISSUE TITLE
vis_stream fail to bring up the viewer GUI

### ISSUE THREAD

**Issue by junechoi93** [labstreaminglayer/App-MATLABViewer#3]
I have a online stream from AudioCaptureWin app running. When typing `vis_stream` to bring up the viewer GUI from Matlab command line, it finishes with an error message like below

`>> vis_stream
Error using supergui (line 122)
supergui error: argument 'fig' must be numeric

Error in inputgui (line 161)
            [tmp tmp2 allobj] = supergui( 'fig', fig, 'minwidth', 200,
            'geomhoriz', g.geometry, 'uilist', g.uilist, 'geomvert',
            [g.geomvert(:)' 1 1] );

Error in arg_guidialog (line 137)
[outs,dummy,okpressed] = inputgui('geometry',geometry,
'uilist',uilist,'helpcom',['env_doc ' helptopic],
'title',dialogtitle,'geomvert',geomvert); %#ok<ASGLU>

Error in vis_stream (line 77)
    arg_guidialog;`

However, the command-line with following options will stream.
`vis_stream('StreamName','AudioCaptureWin', 'DataScale',0.01, 'SamplingRate',500)`

**Comment by Lin-Gao7** [comment]
Hello, I met the same problem as yours, so I want to ask if you solve this problem or not and how did you solve it. Thank you.

**Comment by arnodelorme** [comment]
You can call the function with a parameter to bypass the GUI. For example "vis_stream('timerange', 5)"
